### ISSUE TITLE
Regression tests failed

### ISSUE THREAD

**Issue by weicfd** [the-jet-trio/fprime-editor#25]
**failed test cases in regression test**
26 passing (695ms)
  14 failing

  1) Analyzer invoking should invoke the external analyzer and return given analysis info:
```     
Error: Command failed: ./test//Simple_analyzer_UT/mockChecker undefined
'.' is not recognized as an internal or external command,
operable program or batch file.

      at ChildProcess.exithandler (child_process.js:294:12)
      at maybeClose (internal/child_process.js:970:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
```
  2) Config manager should return project config merged from system config:
```
      AssertionError: expected { Object (Analyzers, FPPCompilerPath, ...) } to deeply equal { Object (Analyzers, FPPCompilerPath, ...) }
      + expected - actual

         "Analyzers": [
           {
             "Name": "AcmeRuleChecker"
             "OutputFilePath": "E:\\JPL\\fprime-editor\\test\\Ref1\\acme_output\\acme_result.css"
      -      "Parameters": "E:\\JPL\\fprime-editor\\test\\Ref1 E:\\JPL\\fprime-editor\\test\\Ref1/acme_output"
      -      "Path": "E:\\JPL\\fprime-editor\\test\\static/mockChecker"
      +      "Parameters": "E:\\JPL\\fprime-editor\\test\\Ref1 E:\\JPL\\fprime-editor\\test\\Ref1\\acme_output"
      +      "Path": "E:\\JPL\\fprime-editor\\test\\static\\mockChecker"
             "Type": "Rule Checker"
           }
         ]
         "AutoLayout": [
           }
         ]
         "DefaultStyleFilePath": "E:\\JPL\\fprime-editor\\test\\Ref1\\mystyle.css"
         "FPPCompilerOutputPath": "E:\\JPL\\fprime-editor\\test\\Ref1\\fpp_output"
      -  "FPPCompilerParameters": "E:\\JPL\\fprime-editor\\test\\Ref1 E:\\JPL\\fprime-editor\\test\\Ref1/fpp_output"
      -  "FPPCompilerPath": "E:\\JPL\\fprime-editor\\test\\static/fppcompiler"
      +  "FPPCompilerParameters": "E:\\JPL\\fprime-editor\\test\\Ref1 E:\\JPL\\fprime-editor\\test\\Ref1\\fpp_output"
      +  "FPPCompilerPath": "E:\\JPL\\fprime-editor\\test\\static\\fppcompiler"
         "ViewStyleFileFolder": "E:\\JPL\\fprime-editor\\test\\Ref1\\styles"
       }

      at Context.it (test\fprime\specs\ConfigManager.spec.ts:91:42)
```
  3) FppModelManager Parsing should load the model when the path contains blank:
```
     Error: Command failed: E:\JPL\fprime-editor\test\Ref2\path\ with\ blank\fppcompiler undefined
'E:\JPL\fprime-editor\test\Ref2\path\' is not recognized as an internal or external command,
operable program or batch file.

      at ChildProcess.exithandler (child_process.js:294:12)
      at maybeClose (internal/child_process.js:970:16)
      at Socket.stream.socket.on (internal/child_process.js:389:11)
      at Pipe._handle.close (net.js:597:12)
```
  4) FppModelManager Query should query the instances and connections in given topology:
```
     TypeError: Cannot read property 'existsSync' of undefined
      at components.forEach.e (src\fprime\FPPModelManagement\FPPModelManager.ts:203:54)
      at Array.forEach (<anonymous>)
      at FPPModelManager.generateText (src\fprime\FPPModelManagement\FPPModelManager.ts:203:54)
      at FPPModelManager.<anonymous> (src\fprime\FPPModelManagement\FPPModelManager.ts:5:1)
      at Generator.next (<anonymous>)
      at fulfilled (src\fprime\FPPModelManagement\FPPModelManager.ts:1:74907)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```
  5) FppModelManager Query should query the related instances and connections in given instance:
```
     TypeError: Cannot read property 'existsSync' of undefined
      at components.forEach.e (src\fprime\FPPModelManagement\FPPModelManager.ts:203:54)
      at Array.forEach (<anonymous>)
      at FPPModelManager.generateText (src\fprime\FPPModelManagement\FPPModelManager.ts:203:54)
      at FPPModelManager.<anonymous> (src\fprime\FPPModelManagement\FPPModelManager.ts:5:1)
      at Generator.next (<anonymous>)
      at fulfilled (src\fprime\FPPModelManagement\FPPModelManager.ts:1:74907)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```
  6) FppModelManager Query should query the related component and ports in given instance:
```
     TypeError: Cannot read property 'existsSync' of undefined
      at components.forEach.e (src\fprime\FPPModelManagement\FPPModelManager.ts:203:54)
      at Array.forEach (<anonymous>)
      at FPPModelManager.generateText (src\fprime\FPPModelManagement\FPPModelManager.ts:203:54)
      at FPPModelManager.<anonymous> (src\fprime\FPPModelManagement\FPPModelManager.ts:5:1)
      at Generator.next (<anonymous>)
      at fulfilled (src\fprime\FPPModelManagement\FPPModelManager.ts:1:74907)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```
  7) FppModelManager Query should query out all the models in the given folder:
```
     TypeError: Cannot read property 'existsSync' of undefined
      at components.forEach.e (src\fprime\FPPModelManagement\FPPModelManager.ts:203:54)
      at Array.forEach (<anonymous>)
      at FPPModelManager.generateText (src\fprime\FPPModelManagement\FPPModelManager.ts:203:54)
      at FPPModelManager.<anonymous> (src\fprime\FPPModelManagement\FPPModelManager.ts:5:1)
      at Generator.next (<anonymous>)
      at fulfilled (src\fprime\FPPModelManagement\FPPModelManager.ts:1:74907)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```
  8) ViewDescriptor should generate cytoscape json:
```
      AssertionError: expected { Object (viewType, needLayout, ...) } to deeply equal { Object (needLayout, elesHasPosition, ...) }
      + expected - actual

           "comp_1_p2"
         ]
         "elesNoPosition": []
         "needLayout": false
      -  "viewType": ""
       }

      at Context.it (test\fprime\specs\ViewDescriptor.spec.ts:608:50)
```
  9) ViewDescriptor should return needLayout = true if missing x/y:
```
      AssertionError: expected { Object (viewType, needLayout, ...) } to deeply equal { Object (needLayout, elesHasPosition, ...) }
      + expected - actual

           "ins_1"
           "ins_2_p1"
         ]
         "needLayout": true
      -  "viewType": ""
       }

      at Context.it (test\fprime\specs\ViewDescriptor.spec.ts:811:50)
```
  10) ViewManager build should print compile message:
```
      AssertionError: expected '\n\r\nE:\\JPL\\fprime-editor>echo "system default compiler..." \r\n"system default compiler..."\r\n\nCovert representation xml...\nGenerate view list...\nTypeError: Cannot read property \'existsSync\' of undefined\n' to equal '\nsystem default compiler...\n\nCovert representation xml...\nGenerate view list...\n'
      + expected - actual


      -
      -E:\JPL\fprime-editor>echo "system default compiler..." 
      -"system default compiler..."
      +system default compiler...

       Covert representation xml...
       Generate view list...
      -TypeError: Cannot read property 'existsSync' of undefined

      at Object.<anonymous> (test\fprime\specs\ViewManager.spec.ts:95:50)
      at Generator.next (<anonymous>)
      at fulfilled (test\fprime\specs\ViewManager.spec.ts:4:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```
  11) ViewManager render should return needLayout = true when a view is first rendered:
```
     TypeError: Cannot read property 'needLayout' of null
      at Object.<anonymous> (test\fprime\specs\ViewManager.spec.ts:129:41)
      at Generator.next (<anonymous>)
      at fulfilled (test\fprime\specs\ViewManager.spec.ts:4:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```
  12) ViewManager updateViewDescriptor should update the cytoscape json:
```
     AssertionError: expected null to deeply equal { Object (needLayout, elesHasPosition, ...) }
      at Object.<anonymous> (test\fprime\specs\ViewManager.spec.ts:155:50)
      at Generator.next (<anonymous>)
      at fulfilled (test\fprime\specs\ViewManager.spec.ts:4:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```
  13) ViewManager getSimpleGraph should return graph for mock REFLogger:
```
      AssertionError: expected {} to deeply equal { Object (#Ref_SG1, #Ref_SG2, ...) }
      + expected - actual

      -{}
      +{
      +  "#Ref_SG1": [
      +    "#Ref_SG1_logTextOut"
      +    "#Ref_SG1_logOut"
      +  ]
      +  "#Ref_SG2": [
      +    "#Ref_SG2_logTextOut"
      +    "#Ref_SG2_logOut"
      +  ]
      +  "#Ref_SG3": [
      +    "#Ref_SG3_logTextOut"
      +    "#Ref_SG3_logOut"
      +  ]
      +  "#Ref_SG4": [
      +    "#Ref_SG4_logTextOut"
      +    "#Ref_SG4_logOut"
      +  ]
      +  "#Ref_SG5": [
      +    "#Ref_SG5_logTextOut"
      +    "#Ref_SG5_logOut"
      +  ]
      +  "#Ref_eventLogger": [
      +    "#Ref_eventLogger_LogRecv"
      +    "#Ref_eventLogger_LogText"
      +  ]
      +  "#Ref_textLogger": [
      +    "#Ref_textLogger_TextLogger"
      +  ]
      +}

      at Object.<anonymous> (test\fprime\specs\ViewManager.spec.ts:192:56)
      at Generator.next (<anonymous>)
      at fulfilled (test\fprime\specs\ViewManager.spec.ts:4:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```
  14) ViewManager saveStyle should save style:
```
      AssertionError: expected false to equal true
      + expected - actual

      -false
      +true

      at Object.<anonymous> (test\fprime\specs\ViewManager.spec.ts:218:33)
      at Generator.next (<anonymous>)
      at fulfilled (test\fprime\specs\ViewManager.spec.ts:4:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**To Reproduce**
run command `nyc mocha --opts ./test/fprime/mocha.opts`

**Comment by weicfd** [comment]
pass 100% when commenting generatText()  function under mac environment

**Comment by weicfd** [comment]
fix the recently failed regression test cases
